### ISSUE TITLE
Sharing all your analysis

### ISSUE THREAD

**Issue by lmguzman** [ropenscilabs/r-docker-tutorial#10]
How can I include this example on the lesson list?

**Comment by ttimbers** [comment]
You want to edit [this](https://github.com/ropenscilabs/r-docker-tutorial/blob/gh-pages/index.html) html file

**Comment by HeidiSeibold** [comment]
And the [README](https://github.com/ropenscilabs/r-docker-tutorial/blob/gh-pages/README.md)

**Comment by lmguzman** [comment]
Great thanks!
