### ISSUE TITLE
max-width not working for Firefox 44.0

### ISSUE THREAD

**Issue by wking** [ropenscilabs/r-docker-tutorial#12]
In Firefox 44.0, the `max-width` property doesn't seem to be working, and images end up unusably wide:

![wide-image](https://cloud.githubusercontent.com/assets/209920/15096020/db0b72d8-149a-11e6-85e3-ec44f967e570.png)

I'm not clear on how Rmd is converted to HTML, but I expect the `max-width` setting comes from [here](https://github.com/ropenscilabs/r-docker-tutorial/blob/7e1292bfb86d01b9d85a3d8a01474b771d62e0fe/stylesheets/styles.css#L156-L157).  The HTML for the page nests the image inside a figure `div`:

``` sh
$ curl -s http://ropenscilabs.github.io/r-docker-tutorial/01-what-and-why.html |
>   grep -1 Computerception | sed 's/src="[^"]*"/src="..."/g'
<div class="figure">
<img src="..." alt="Computerception" />
<p class="caption">Computerception</p>
</div>
```

The figure class is configured (I'm not sure how) to display as a table:

![figure-table](https://cloud.githubusercontent.com/assets/209920/15096026/7d764688-149b-11e6-8249-8230d6feee43.png)

Disabling (via the inspector checkbox) that table-display property gets `max-width` working again:

![figure-table-disabled](https://cloud.githubusercontent.com/assets/209920/15096037/01dd642e-149c-11e6-9a29-a85f48fc6c03.png)

MDN mentions [`max-width` with `table` being undefined](https://developer.mozilla.org/en-US/docs/Web/CSS/max-width#Browser_Compatibility), although whether that applies to `display: table` is unclear to me.  I'm not clear on why you'd want `display: table` anyway, so if someone can find where it's coming from and how to disable it, that would probably be a reasonable fix for the Firefox rendering.

For what it's worth, the current page renders fine in Chromium 48.0:

![chromium](https://cloud.githubusercontent.com/assets/209920/15096062/ccc784f8-149c-11e6-8f2a-33dbeabd60f6.png)

**Comment by fmichonneau** [comment]
I can't reproduce this in Firefox 46.0 (Ubuntu 16.04). The image is
correctly scaled and is being reduced if the window size decreases.

**Comment by katieannemills** [comment]
Reproduces on FF 45.0.1 / OSX 10.10.3; +1 to removing `display: table`, this is a webby no-no; table are for _tables_, and nothing else. I will look into doing this possibly later today.

**Comment by katieannemills** [comment]
Fixed ala https://github.com/karthik/dcTemplate/pull/1?

**Comment by ttimbers** [comment]
@wking - can you let us know whether you still have this issue on Firefox 44.0?

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 03:36:02PM -0700, Tiffany Timbers wrote:

> @wking - can you let us know whether you still have this issue on
> Firefox 44.0?

No, [1](http://ropenscilabs.github.io/r-docker-tutorial/01-what-and-why.html) looks good now.

**Comment by ttimbers** [comment]
@wking Excellent! Thanks for checking!
