### ISSUE TITLE
Bug BBQ Goals

### ISSUE THREAD

**Issue by katieannemills** [ropenscilabs/r-docker-tutorial#14]
Hi team,

The [Software Carpentry Bug BBQ](http://swcarpentry.github.io/SWC-bug-bbq/) is coming up! If we want to participate, we need to lay out a roadmap of goals for the event. I think it would make sense to try and get things to a testable beta state by the end of the BBQ - what do all y'all think?

To participate in the BBQ, we need to make issues noting all the things we need to do to get from where we are now, to where we want to be (ie a decent draft). Maybe we (I'm looking at @Emaasit @wking @ttimbers @HeidiSeibold @lmguzman and myself, and anyone else who wants to jump in) can all have a read and point out:
- what parts are outright missing?
- are there any inconsistencies between sections (ie telling people to install r packages one way at one time and another way later)?
- do the commands actually work as written?
- are there adequate challenge problems in all sections?
- _________ (other mission-critical questions I forgot)

Plus anything else you want to raise - but if we identify all those places that need work (like, just _identify_ them - you don't need to fix them, that's what we'll do on the Bug BBQ) say by June 8 or so, we can put together a clear picture of what we want to achieve on the 13th. Sound good?

**Comment by HeidiSeibold** [comment]
Sounds good. I'm in.

**Comment by christophM** [comment]
Finally I got myself trying out Docker thanks to your nice tutorial. @HeidiSeibold brought me here. 

I  found a few things for which I will open issues.

**Comment by katieannemills** [comment]
Thanks, @christophM - glad to have you on board!

I've picked through the lesson just now, see my comments in #19 - #23 and #8. Altogether I think we're in great shape; the executive summary is: 
- **challenge problems**. I gave some high-level (vague) suggestions in each section, and I'm hoping the R heroes on this project will have the specific domain knowledge to make something compelling happen there. 
- **consistency check**, most of the problems being in my `05`, which I will deal with on the day of the BBQ. 
- **compelling examples** of these tools and workflows out in the wild to get people excited about the opportunities
- **capstone tuneup** in section `06` - it's quite good as it is, but I think we could go one last mile to make it more authentic with some data and real packages.

Other comments and perspectives this week before the BBQ would be awesome! Maybe we can use the issues I listed above for general comments on each chapter, and more specific things can get their own issues? Let us know, can't wait to sprint on this in a week!

**Comment by HeidiSeibold** [comment]
Since I will not have all that much time on the 13th I would start to do things during this week. If nobody objects I would just start implementing the things we talk about in the issues. Should I open a new branch, so it is easier to track?

**Comment by ttimbers** [comment]
Great idea to get started ahead of the 13th! Sure, a branch for your changes sounds good, and then send the changes to gh-pages as a PR. Thanks!

**Comment by HeidiSeibold** [comment]
Regarding the point

> -  **compelling examples** of these tools and workflows out in the wild to get people excited about the opportunities

I actually was not able to find very much. Maybe some of us have interesting examples? 

I'm not sure if this is interesting, but I have
- a Dockerfile to set up my usual [research project](https://hub.docker.com/r/heidiseibold/research-project/~/dockerfile/) base (with subversion, R, RStudio, latex, knitr, rJava, ggplot2 and plyr) that I need for basically every project I do.
- a Dockerfile to work on my [blog](https://github.com/HeidiSeibold/HeidiSeibold.github.io/blob/master/_build/Dockerfile) (Jekyll, RMarkdown, Git and Github) easily from both my Computers (and possibly new ones) without having to go through the process of installing everything - especially jekyll.

Feel free to use those as example although I think at least the second might be a little out of scope.

**Comment by znmeb** [comment]
@HeidiSeibold IMHO Rocker and the OpenCPU Dockerfiles are pretty compelling on their own.

**Comment by katieannemills** [comment]
@HeidiSeibold I like your research project example! That's really authentic and relevant for our students, I'm going to work that in.

**Comment by katieannemills** [comment]
Thinking about this further, I think this is most relevant to section `06`, which @lmguzman is working on presently. Melissa, could you work in a challenge problem that uses @HeidiSeibold's [Dockerfile here](https://github.com/HeidiSeibold/dockerfiles/blob/master/research-project/Dockerfile), maybe getting folks to build it locally and run it - @HeidiSeibold, is there something cool / visual / fun they could run in that container once it's built to see it all working?

**Comment by HeidiSeibold** [comment]
Sorry, it was already late for me when you wrote this. One could compile a little knitr file including a ggplot maybe?

**Comment by jsta** [comment]
Cleaning up old/stale issues and PRs. Happy to revisit if someone gives the word.
