### ISSUE TITLE
Create nice version of Computerception graphic

### ISSUE THREAD

**Issue by christophM** [ropenscilabs/r-docker-tutorial#16]
The ['Computerception'-graphic draft](https://github.com/ropenscilabs/r-docker-tutorial/blob/gh-pages/files/computer.jpg) might need a nicer version.

**Comment by christophM** [comment]
No offense @HeidiSeibold or whoever drew it. =)

**Comment by HeidiSeibold** [comment]
None taken. Thanks for helping :)

**Comment by HeidiSeibold** [comment]
[computerception.pdf](https://github.com/ropenscilabs/r-docker-tutorial/files/300511/computerception.pdf)

Better? Or is anyone a better artist maybe?

**Comment by katieannemills** [comment]
resolved in #24
