### ISSUE TITLE
Maybe add some instructions on autobuilds

### ISSUE THREAD

**Issue by znmeb** [ropenscilabs/r-docker-tutorial#18]
In my readings on Docker, I've seen numerous references to "don't push images to Docker Hub; use autobuilds on Docker Hub instead". This is mostly a trust issue - if people can look at the Dockerfile and see what's in the image they're more inclined to trust it for a pull than if it's just "somebody with an account pushed an image".

There's also a bandwidth issue - many ISPs provide vastly lower upload speeds than download speeds. For example, my Comcast has 60 megabits down and only 6 megabits up.

Once you have an image building locally it's easy to set up an autobuild on Docker Hub or Quay.io. 

Docker Hub: https://docs.docker.com/docker-hub/builds/
Quay.io is a bit more complicated; I use it because they track GitLab and Docker Hub only tracks GitHub and Bitbucket.

**Comment by katieannemills** [comment]
This is awesome, thanks for pointing it out! I was personally unaware of this feature, and kind of unsatisfied with the fact that I had a Dockerfile hanging out on GitHub and an image way over on Dockerhub with precious little to connect the two.

I think this is a great candidate for a supplemental section; it's super useful, but relies on the student being okay with git, which will totally torpedo a lot of folks at the level we're shooting for. Nonetheless, I am totally game to pull something together here as bonus material. Thanks much!

**Comment by katieannemills** [comment]
implemented in #33
