### ISSUE TITLE
Section 02 minor comments

### ISSUE THREAD

**Issue by katieannemills** [ropenscilabs/r-docker-tutorial#19]
I think overall `02-Launching-Docker` is in good shape for our first release. Here's what I would change, though none of this is mission-critical:
- In 'Launching R Studio in Docker', move `docker run --rm -p 8787:8787 rocker/hadleyverse` to before the optional comments. This encourages the instructor to get something on the screen asap - they can editorialize about it while the helpers go around and get people unstuck, rather than keeping students in 'wait and listen' mode before getting the first command of the section.
- In the same section, most students won't know what a 'port' is. Something like "`-p` stands for _port_, and tells Docker we'd like to visit RStudio in our web browser. The `8787:8787` will be part of the URL RStudio will be visible at, as we'll see right away."
- When introducing the `-v` flag, we currently ask the student to figure out what directory on their physical machine they want to mount - maybe remind them to `pwd`? Actually, they can even go `-v $PWD:/whatever/mount/point`, though maybe that syntax is a bit much; in any case, asking students to deftly wield the shell knowledge they just learned is usually a stretch, so some reminder about pwd is probably in order.

Also - challenge problems. Can we rely on these folks to have RStudio installed on their local machines? If so, they could buddy up, open local RStudio, and compare the results of `installed.packages()`, then do the same in their docker-rstudio - or something similar that illustrates the perfect consistency of a shared docker container versus the wild west of whatever people happen to have installed. Is anyone aware of a behavior change between a couple of different versions of any given r package we could illustrate in a similar exercise?

**Comment by HeidiSeibold** [comment]
The most likely have R installed, right? Why would they be doing this tutorial otherwise?
