### ISSUE TITLE
Section 03 challenges

### ISSUE THREAD

**Issue by katieannemills** [ropenscilabs/r-docker-tutorial#20]
`03-install-packages` is good-to-go IMO, but it of course needs challenges. Ideas?

The thing that makes me a bit anxious about the whole `docker commit` workflow is that it leaves you with an image with goodness-knows-what inside it, as we get super philosophical about in #11. I'd like to see a challenge problem that walks people through generating some docs about what's in this image, and then baking that into the image. Something like 
- add the response of `installed.packages()` to a file
- ________ (something to capture whatever got `apt-get'ed` or whatever else outside of R)
- save the file as a `README` in your image.

**Comment by znmeb** [comment]
@BillMills Do people actually use the "docker commit" workflow outside of a beginner / class environment? I was using Dockerfiles the second day. Would it slow things down unacceptably to say, "build a Dockerfile for the first exercise"?

**Comment by cboettig** [comment]
@znmeb Good question; I also wonder which is best to teach; I agree `docker commit` is more black box (though if you commit often, you can read back the individual commands run on the instance via `docker history`).

Just as answer to your question though, one use I often have for `docker commit` is when using separate data volumes, e.g. https://github.com/cboettig/2015/blob/master/_build/local.sh#L53

**Comment by znmeb** [comment]
@cboettig Yes, I have "docker commit" in my bash scripts to do a save after, e.g., setting a password. ... and I should look at your data volume code - I have an open issue on my main Docker project to do just that!

**Comment by katieannemills** [comment]
@znmeb I was kind of ho-hum on `docker commit` at first too, but after reading this lesson the way it's coming together, I see there are two big use cases here:
- the 'freeze-it-in-amber' approach, where someone has done a bunch of work and now wants to tie everything up into a repeatable image.
- the 'portable infrastructure' approach, which focuses on making a stack easy to carry around.

`docker commit` makes a lot of sense for the first (since there I want to take a snapshot of things that already exist), while Dockerfiles make sense for the second (since I may want to change my stack in a well documented way in future). I was very much in the second camp at first, but I see the value of the first for the reproducible science crowd (who are a big big part of the base of people who will see this lesson).

It does make sense however to build a dockerfile for this image as an exercise for after the dockerfiles chapter, though!

**Comment by katieannemills** [comment]
I'm satisfied with the challenges in `03` - feel free to add more, but I think we're good for a first pass here after @HeidiSeibold's pull.
