### ISSUE TITLE
Section 04 challenges

### ISSUE THREAD

**Issue by katieannemills** [ropenscilabs/r-docker-tutorial#21]
`04-Dockerhub` is in good shape, but also needs challenges. Off the top of my head:
- download your partner's image. How did that compare speed-wise to downloading the hadleyverse image the first time? (_It was super fast since docker is smart enough to not re-download the base hadleyverse image, and only had to grab your changes_).
- something about searching dockerhub for an interesting project?

also I assume `04-commit` can be abandoned as `04-dockerhub` covers that material?

**Comment by HeidiSeibold** [comment]
> also I assume 04-commit can be abandoned as 04-dockerhub covers that material?

I think so, yes.

**Comment by HeidiSeibold** [comment]
Challenges sound good to me.
