### ISSUE TITLE
teaching tips

### ISSUE THREAD

**Issue by katieannemills** [ropenscilabs/r-docker-tutorial#23]
Most SWC/DC lessons come with a supplemental 'teaching tips' file, which provide guidance to the instructor on pitfalls to avoid, techniques for getting people involved etc. Since no one has actually taught this yet, there might not be a ton to put here, but even just a stub will provide a target for people to push their tips at in future. For example:
- section 1
  - lead a 5 min discussion to help students imagine where they'll use Docker. Places to guide the conversation towards if they're stuck: department clusters, cloud services, their new computer etc.

**Comment by HeidiSeibold** [comment]
We have some Instructor Notes in the readme, which are:
-  Bring thumb drives with the docker images. If a bunch of people want to download the same 3GB image you might run into problems.
- Optional parts are marked with the word "Optional:" and italic text.
