### ISSUE TITLE
Do you want to include instructions on sharing images via "docker save" and "docker load"?

### ISSUE THREAD

**Issue by znmeb** [ropenscilabs/r-docker-tutorial#25]
Pushing to Docker Hub is great, but it does have some disadvantages:
1. Bandwidth - many ISPs have _much_ lower upload bandwidth than download bandwidth. For example, my home Comcast has a luxurious 60 mbits / second down but only 6 mbits / second up!
2. Unless you're paying extra for the private repositories, pushing equals publishing.

For local interchange of Docker images, there's an alternative - `docker save` saves an image to a tar archive and `docker load` loads an image from a tar archive. One collaborator can save an image to a tar archive on a USB stick and the second can load the image, or the archives can be stored on a local shared file server.

**Comment by ttimbers** [comment]
I agree! In addition to sharing with others, I have had to use these commands when working on a cluster, as each time a logged into a node, I would have to pull my Docker image from Docker Hub and this took a long time. So instead I saved my docker image in my project space, and used `docker load` everytime I ran a job.

**Comment by ttimbers** [comment]
Let's add `docker save` and `docker load` to [Lesson 04 Pushing and Pulling with Docker Hub](https://github.com/ropenscilabs/r-docker-tutorial/blob/gh-pages/04-Dockerhub.Rmd)

**Comment by katieannemills** [comment]
Thanks team, sounds good!

**Comment by katieannemills** [comment]
implemented in #34, well done all.
