### ISSUE TITLE
Two different section 4's

### ISSUE THREAD

**Issue by bsmith89** [ropenscilabs/r-docker-tutorial#29]
Both `04-commit.Rmd` and `04-Dockerhub.Rmd` exist.  `04-commit.Rmd` has a link to the "next lesson" 05-Dockerhub, which is not a thing.

**Comment by katieannemills** [comment]
Right! `04-commit` has been replaced with other stuff, so we should just remove it.

**Comment by katieannemills** [comment]
aaaand done. Thanks for reminding me!
