### ISSUE TITLE
Linking a volume to a Docker container different in Linux

### ISSUE THREAD

**Issue by HeidiSeibold** [ropenscilabs/r-docker-tutorial#3]
@ttimbers [this](https://github.com/ropenscilabs/r-docker-tutorial/blame/447776db2c12298f18ce8591a35e2b4c0dc07ca0/02-Launching-Docker.Rmd#L117) does not work for me.

I need to have /home/rstudio on the right hand side for the my files to show

```
docker run --rm -p 8787:8787 -v ~:/home/rstudio/heidisfiles rocker/hadleyverse
```

Is that Linux specific?

**Comment by ttimbers** [comment]
No, this is not linux specific. I have pushed a fix. You are correct that container paths **must** start with `/home/rstudio/`
