### ISSUE TITLE
More Explicit Docker Install Instructions 

### ISSUE THREAD

**Issue by marschmi** [ropenscilabs/r-docker-tutorial#31]
The first step in **Lesson 02 Launching Docker** is to install docker.  As SWC/DC workshop participants often have installation problems, it might be efficient to be explicit regarding the installation of docker before the lesson gets started.  

I suggest either:  
1. Include the install instructions on the main page of the lesson, or  
2. Add a **Lesson 00 Installing Docker** section

Either of these options would help make sure that participants have installed it before the lesson begins.

**Comment by katieannemills** [comment]
Better pointers to the install instructions are definitely a good idea, I like the idea of putting a big bold link on the main page. I don't want to reproduce the steps ourselves though, since they can change at Docker's whim - and why not let them maintain those instructions for us?
