### ISSUE TITLE
Were do we get gapminder-FiveYearData.csv?

### ISSUE THREAD

**Issue by HeidiSeibold** [ropenscilabs/r-docker-tutorial#4]
We should mention where the [data](https://github.com/ropenscilabs/r-docker-tutorial/blame/447776db2c12298f18ce8591a35e2b4c0dc07ca0/02-Launching-Docker.Rmd#L126) comes from.

**Comment by ttimbers** [comment]
This lives in the `data` directory of this repository. When we are teaching the students we would provide them the data.
