### ISSUE TITLE
initial run of "docker run rocker/rstudio" results in an unique password error.

### ISSUE THREAD

**Issue by jasongrahn** [ropenscilabs/r-docker-tutorial#48]
https://github.com/ropenscilabs/r-docker-tutorial/blob/a57625fdc111ba2c18311012324b214b82e18338/02-Launching-Docker.Rmd#L49

Repro: 
launch docker
copy/paste command to terminal 
docker downloads the appropriate image files
receive error

```
[cont-init.d] userconf: executing...

ERROR: You must set a unique PASSWORD (not 'rstudio') first! e.g. run with:
docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio

[cont-init.d] userconf: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Two suggestions: 

1. the information changes to instruct users to come up with a unique password for the command.
2. line 49 be updated to reflect the command supplied by the error message.

**Comment by jsta** [comment]
Solved by #55
