### ISSUE TITLE
This repository will be archived unless someone adopts it

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/r-docker-tutorial#56]
Cf our [curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages)

Cc initial contributors @BillMills @ttimbers @lmguzman @Emaasit 

And cc @HeidiSeibold

**Comment by nuest** [comment]
@maelle Can you clarify "adoption", please? Do you mean transfer to personal account, or doing some updates and housekeeping here? The tutorial is pretty basic, but many tutorials move too quickly into complex topics, so this might be worth keeping around.

**Comment by maelle** [comment]
Sorry for being unclear. I mean transferring to a personal account, yes. We could have some sort of redirect for gh-pages I suppose.

**Comment by maelle** [comment]
@nuest would you be up for maintaining this tutorial at your personal account?

**Comment by maelle** [comment]
@nuest do you want me to transfer the repo to your account?

If you don't answer within one week I'll transfer this to ropensci-archive, after which you can still email me for requesting transfer to a personal account.

**Comment by jsta** [comment]
Does archiving mean the ghpages site would go away? If yes, I would be interested in adoption.

**Comment by maelle** [comment]
@jsta transfer requested! After you accept it and set up a gh-pages site on your end, I'll redirect the current URL to yours.

**Comment by jsta** [comment]
@maelle Done

**Comment by maelle** [comment]
redirect set up for https://ropenscilabs.github.io/r-docker-tutorial so I think we're good. Thank you @jsta!
