### ISSUE TITLE
Good practices with tags

### ISSUE THREAD

**Issue by HeidiSeibold** [ropenscilabs/r-docker-tutorial#7]
https://github.com/ropenscilabs/r-docker-tutorial/blame/6c823e3f5d96a6fdcf966d0dae312d6aa4460022/04-Dockerhub.Rmd#L83

**Comment by katieannemills** [comment]
I like the gist of [ @cboettig's point ](http://www.carlboettiger.info/2014/08/29/docker-notes.html) that tags (or version tags) are useful for connecting an image to something else, like a git sha (or a doi, an arXiv index...). I'll send something along shortly in this spirit.

**Comment by jsta** [comment]
Looks like this was solved by #35. Happy to revisit if someone gives the word.
