### ISSUE TITLE
TODOs in chapter 5-Dockerfiles

### ISSUE THREAD

**Issue by HeidiSeibold** [ropenscilabs/r-docker-tutorial#8]
[Line 17](https://github.com/ropenscilabs/r-docker-tutorial/blame/70a2fb0007eb5dfe6f802ec1cae9b70a13095582/05-dockerfiles.Rmd#L17)

and 

[Line 53](https://github.com/ropenscilabs/r-docker-tutorial/blame/70a2fb0007eb5dfe6f802ec1cae9b70a13095582/05-dockerfiles.Rmd#L53)

**Comment by katieannemills** [comment]
Line 53: we may not have actually mentioned this yet (sorry, this text is a direct copy-paste from my tutorial, I figured we'd have to come back and smooth stuff like this out) - but we need to decide if / how / when we want to teach container management skills like these. The comment inline with the TODO to press `ctrl-c` won't actually kill the container; try doing

```
docker ps -a
```

and you'll see all your old containers still hanging around in various states.

Line 17: similar artefact from the origin of this text; I see you've settled on `rocker/hadleyverse` - a fine choice, I will update section 5 accordingly.

**Comment by HeidiSeibold** [comment]
> (sorry, this text is a direct copy-paste from my tutorial, I figured we'd have to come back and smooth stuff like this out)

No problem. I just wanted to make sure we revise it :)

> we need to decide if / how / when we want to teach container management skills like these.

I agree. Haven't made up my mind about this. So if anyone has suggestions I would happily implement them

>  I will update section 5 accordingly.

Thanks!

**Comment by ttimbers** [comment]
@cboettig and I had decided to run all our docker run commands with --rm for this lesson. This makes the containers ephemeral and then we do not need to overly complicate things and teach container management. Thoughts @BillMills @HeidiSeibold?

**Comment by HeidiSeibold** [comment]
I guess I have no strong opinions on these things yet since this is all still very new to me. As I understand from the manual 
https://docs.docker.com/engine/reference/run/#clean-up-rm
not using --rm is only important for debugging. In cases where we want to do analyses on the docker container interactively (as we teach it in the tutorial) it should thus make sense to use --rm every time.

Did I understand that correctly?

**Comment by ttimbers** [comment]
@HeidiSeibold I think you did, and so let's keep using --rm. I think it is a best practice, and when students learn more about Docker and need containers to persist, they then should know enough to be able to find out about cleaning up containers. What do you think @BillMills ?

**Comment by katieannemills** [comment]
+1 TIL

**Comment by katieannemills** [comment]
Other todos for the BBQ:
- [x] resolve comments above
- [x] rejig intro to acknowledge that we already added deps in `03`, and this is a different way to build containers; include some general motivation
- [x] install `gapminder` with some more R-approved tool, as opposed to wgetting the source
- [x] double check that all commands corresponding to earlier sections are syntactically identical
- [x] proofread backreferences
- [x] use the data from this lesson instead of a new `data.dat` file
- [ ] pointer to supplemental material discussed in #18 (also write that supplemental material)
- [x] aaaaaand challenge problems.

**Comment by HeidiSeibold** [comment]
Maybe a challenge (in the spirit of #18) could be:
- Find the Dockerfile of the hadleyverse image (which is linked on dockerhub)

**Comment by katieannemills** [comment]
haha merge gong show - don't forget to `git pull` folks :) Anyway, this is resolved in #28 if someone would like to review and merge.
